#=================================OOO====================================#
#                     TabList Configuration File                         #
#=================================OOO====================================#
# config.yml file. Plugin version: 2.4.7                                 #
# Author, created by: montlikadani                                       #
#=================================OOO====================================#
# [Default configurations]                                               #
# https://github.com/montlikadani/TabList/blob/master/config.yml         #
#                                                                        #
# [Placeholders]                                                         #
# https://www.spigotmc.org/wiki/placeholderapi-placeholders/             #
#                                                                        #
# [Other placeholders]                                                   #
# https://github.com/montlikadani/TabList/wiki/Placeholders              #
#                                                                        #
# [Tips]                                                                 #
# - Use color coding '&' character, on this page:                        #
# http://minecraft.gamepedia.com/Formatting_codes                        #
# - In case of an error, write here:                                     #
# https://github.com/montlikadani/TabList/issues                         #
# - Use symbols in messages, on this page:                               #
# https://github.com/montlikadani/TabList/wiki/Symbols                   #
#=================================OOO====================================#

# If these number mark (#) are in the way, you can safely remove it.

#=========================================#
#                Settings                 #
#=========================================#
# PlaceholderAPI use for the plugin.
placeholderapi: true

# Different playerlist in different world.
per-world-player-list: false

# Remove the NPC name from the tab?
# ATTENTION! This is currently under repair and testing...
remove-npc-name-from-tab: false

# Time format.
# Formats/examples: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
time-format: 'yyyy.MM.dd - HH:mm:ss'

# Custom variables.
# Unlimited variables.
# Use: <something>: '&6Message...'
custom-variables:
  <website>: 'example.com'
  <name>: '&r%player_name%'
  <pluginauthor>: '&amontlikadani'
  <rightarrow>: '-->'

# Enables to change prefix & suffix in player tablist.
change-prefix-suffix-in-tablist: true

# Groups refresh interval. (In ticks!)
groups-refresh-interval: 200

# This indicates the ping for the player's name.
# WARNING! First, you must disable the "health-tab" because it merges and causes a bug.
ping-tab:
  enable: false
  # Ping update time interval.
  interval: 3
  # Which worlds do not show up in ping (world names)? If you do not want to disable any of them, use this: disabled-worlds: []
  disabled-worlds: []

# Player tab name.
tabname:
  # Allow change player tab name.
  # Warning if this is false, the command will not be registered either. Requires server restart!
  enable: false
  # How many letters should be allowed?
  max-name-length: 200
  # When the player left the server, delete the tab name?
  clear-player-tabname-on-quit: false
  # Enables color coding for tab names. ("&")
  enable-color-code: true
  # Enable the default color. (If the player has not written a color code, this color will be given by default.)
  default-color:
    enable: false
    color: '&6'
  # Which worlds can not change a tab name?
  # If you do not want to disable it, use it as follows: disabled-worlds: []
  disabled-worlds: []
  # Which names can not be used?
  # If all the words are used, set it as follows: blacklist-names: []
  # WARNING! Color codes are NOT considered.
  blacklist-names:
  - tabname
  enable-other-changed-name-message: false
  # Use %name%, %sender%, %newline%, %prefix% placeholder.
  # >> NO supported the PlaceholderAPI! <<
  other-changed-name-message: '&3Your name is changed to&r %name%&3 by&e %sender%&3.'

# Allow the tab to set the level of life (health)?
# WARNING! This only appears in the server after reconnecting.
# WARNING! First, you must disable the "ping-tab" because it merges and causes a bug.
health-tab:
  enable: false
  # Which worlds show your health in tab?
  # If you do not want to disable any of the worlds, then write it as follows: disabled-worlds: []
  disabled-worlds:
  - world_the_end

# Tablist. Header & footer with animation.
# Use \n, %staff-online%, %ip-address%, %level%, %xp%, %mc-version%, %motd%, %ping%, %servername%, %online+1%,
# %max-players%, %online-players%, %server-time%, %server-ram-free%, %server-ram-max%, %server-ram-used% placeholders.
# Use placeholders: https://www.spigotmc.org/wiki/placeholderapi-placeholders/
# Use symbols: https://github.com/montlikadani/TabList/wiki/Symbols
tablist:
  # Enable the tab? (Header, footer)
  enable: true
  # What world does not display the tab?
  # If you do not want to disable any of the worlds, then write it as follows: disabled-worlds: []
  disabled-worlds:
  - lobby
  - hub
  # Tab update time interval.
  # Set 0 to disable.
  interval: 4
  header:
    - '&b&lTabList\n&7    <75>&c W&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&6&lTabList\n&7    <75>&c We&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&4&lTabList\n&7    <75>&c Wel&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&9&lTabList\n&7    <75>&c Welc&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&a&lTabList\n&7    <75>&c Welco&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&e&lTabList\n&7    <75>&c Welcom&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&5&lTabList\n&7    <75>&c Welcome&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&b&lTabList\n&7    <75>&6 Welcome&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&6&lTabList\n&7    <75>&7 Welcome&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&4&lTabList\n&7    <75>&4 Welcome&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&9&lTabList\n&7    <75>&a Welcome&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&a&lTabList\n&7    <75>&b Welcome&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&e&lTabList\n&7    <75>&9 Welcome&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&5&lTabList\n&7    <75>&f Welcome&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&b&lTabList\n&7    <75>&f Welcom&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&6&lTabList\n&7    <75>&f Welco&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&4&lTabList\n&7    <75>&f Welc&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&9&lTabList\n&7    <75>&f Wel&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&a&lTabList\n&7    <75>&f We&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&e&lTabList\n&7    <75>&f W&5&o %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&5&lTabList\n&7    <75>&f&5&o  %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
    - '&b&lTabList\n&7    <75>&f&5&o  %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
  footer:
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&6&o W&f&oebsite&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o W&6&oe&f&obsite&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o We&6&ob&f&osite&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Web&6&os&f&oite&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Webs&6&oi&f&ote&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Websi&6&ot&f&oe&7:&2 &nexample.com&7 <28>'
    - '&5&m======================&7\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Websit&6&oe&7:&2 &nexample.com&7 <28>'
  # Per world tablist.
  # Unlimited world.
  per-world:
    enable: false
    world_nether:
      header:
        - '&3This is a per world plugin&6 Tab&aList&3.'
      footer:
        - '&6World:&7 %player_world%'
    world:
      header:
        - '&cThis is a per world plugin&6 TabList'
        - '&6This is a per world plugin&3 TabList'
        - '&3This is a per world plugin&a TabList'
        - '&aThis is a per world plugin&7 TabList'
      footer:
        - '&6World:&7 %player_world%'

#=========================================#
#             Plugin Settings             #
#=========================================#
# The TabList plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %newline%, %prefix% placeholder.
# >> NO supported the PlaceholderAPI! <<
plugin-enable-message: true
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v2.4.7&a!'
plugin-disable-message: true
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# The default is allowed to see the plugin information.
# Permission: tablist.plugininfo
default-can-see-plugin-information: false

# Unknown-command - If more than one word/letter you write to it.
# Example: /tl reload something...
# Use %command% placeholder.
# This feature is NOT enter into the unknown command Minecraft, it's just your own.
# >> NO supported the PlaceholderAPI! <<
unknown-command-enable: true
unknown-command: '%prefix%&c Unknown command.&7 Type "&f/%command% help&7" for help.'
