# Hooks to another plugins
hook:
  # Hook to PlaceholderAPI to use custom placeholders.
  placeholderapi: true

  # Hook to my RageMode plugin. (https://www.spigotmc.org/resources/69169/)
  # If true, then tablist, groups and tablist objects will be disabled while
  # running a game.
  RageMode: false

# Different player list in different world.
per-world-player-list: false

# Fake players that can be added to the player list.
enable-fake-players: false

# If enabled, the gray color will not appear to other players when the player's game mode is spectator.
# The gray color will only show for the spectator player.
# Requires ProtocolLib!
remove-gray-color-from-tab-in-spectator: false

# true - does not count vanished players in %online-players% placeholder.
# Requires Essentials, SuperVanish or CMI plugin!
ignore-vanished-players-in-online-players: false

# true - count vanished staff in %staff-online% placeholder,
# but they need to have "tablist.onlinestaff" permission set.
# false - does not count vanished staff in the %staff-online% placeholder
# Requires Essentials, SuperVanish or CMI plugin!
count-vanished-staffs: true

# Hide player from player list when he is AFK?
# Requires Essentials or CMI plugin!
hide-player-from-tab-when-afk: false

# Hide all players from the player list?
# This removes all players from the player list, but the player that has the
# group set is retained as it is not changed during removal, so your group
# will be restored if this option is disabled.
# The "per-world-player-list" will not work if this is enabled.
hide-players-from-tablist: false

# Placeholders formatting
placeholder-format:
  # When the player changes the AFK status, change his tablist name format?
  afk-status:
    enable: false

    # Should the AFK format display in right or left side?
    # true - displays in right side
    # false - displays in left side
    show-in-right-or-left-side: true

    # Show player's group if the player is AFK?
    show-player-group: true

    # Format when the player is AFK.
    format-yes: "&7 [AFK]&r "
    # Format when the player is not AFK.
    format-no: ""

    # Sort AFK players to the bottom of the player list?
    sort-last: false

  time:
    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    # Or google it: "what is my time zone"
    time-zone: "GMT0"

    # Use system default time zone instead of searching for that?
    use-system-zone: false

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Format of %server-time% placeholder.
    time-format:
      format: "mm:HH"
    # Format of %date% placeholder.
    date-format:
      format: "dd/MM/yyyy"

  # Ping color format for %ping% placeholder.
  ping:
    enable: true
    good-ping:
      color: "&a"
      amount: 200
    medium-ping:
      color: "&6"
      amount: 500
    bad-ping: "&c"

  # TPS color format for %tps% placeholder.
  tps:
    # How many numbers do you want to display after "." in %tps% placeholder?
    # The number should be higher than 0.
    # Example: 3 = 20.14
    size: 2

    enable: true
    good-tps:
      color: "&a"
      amount: 18.0
    medium-tps:
      color: "&6"
      amount: 16.0
    bad-tps: "&c"

# Enable changing of prefix & suffix in player list?
# This option generates the groups.yml file.
change-prefix-suffix-in-tablist:
  enable: true

  # Refresh interval in seconds, if using animation then it counts in ticks.
  # Set to 0 if you don't want to refresh the groups.
  # If 0, then you will need to execute the /tl reload command to refresh the groups.
  refresh-interval: 30

  # Do you want to use animation in groups?
  # If true, you need to change the refresh-interval such as 4, because it will count in ticks.
  # If false, interval counts in seconds.
  enable-animation: false

  # Disable groups in these worlds.
  disabled-worlds:
    # Use the list as whitelist?
    use-as-whitelist: false
    list:
    #- myWorld

  # Automatically add groups from another plugins to the tablist groups.yml on every reload?
  # If a plugin does not support Vault, it will not be added.
  sync-plugins-groups-with-tablist: true

  # This option allows plugin to use a different scoreboard to run groups if there is a conflict
  # with other scoreboard plugins. If it doesn’t happen that the scoreboard disappears,
  # you don’t need to enable this.
  use-own-scoreboard: false

  # Hide player's group in player list when the player is vanished?
  # Requires Essentials, SuperVanish or CMI plugin!
  hide-group-when-player-vanished: false

  # Hide player's group in player list when the player is AFK?
  # Requires Essentials or CMI plugin!
  hide-group-when-player-afk: false

  # Use another plugin nickname instead of player's original name?
  # true - Using this format: "prefix playerNickName suffix"
  # false - Using this format: "prefix playerOriginalName suffix"
  # Requires Essentials or CMI plugin!
  use-plugin-nickname: false

  # Use tab name instead of player's original name?
  use-tab-name: false

  # Prefer player's primary Vault group when assigning tablist group from groups.yml?
  # true - player will be assigned their primary vault group where possible, after that
  # groups from groups.yml will be applied in descending order.
  # false - groups from groups.yml will be applied in descending order.
  prefer-primary-vault-group: true

# Tablist objective types
# Shows your current health (with life indicator), your current ping or any NUMBER placeholder
# after the player's name (before the ping indicator).
tablist-object-type:
  enable: true

  # Types:
  # ping - player's ping
  # health - player's health
  # custom - custom placeholder
  type: ping

  # Interval for objects refreshing. In seconds.
  # Note: The health is not updating auto due to display issues.
  refresh-interval: 3

  # In these worlds the objects will not be displayed
  disabled-worlds:
  #- testingWorld

  # Objective settings
  object-settings:
    # The player's health - displayed after the player's name.
    health:
      # For these players the health will not be displayed
      restricted-players:
      - exampleplayer
      - players

    # Custom placeholder - accepts only number-ending placeholders, like %level%.
    # If it is double-number ending, it will remove the dot "." from the number.
    custom:
      value: "%level%"

# Changing player's tablist name with unlimited characters.
tabname:
  # Allow to change player's tab name?
  enable: false

  # Use another plugin nickname instead of tab name?
  # Requires Essentials or CMI plugin!
  use-plugin-nickname: false

  # How many characters should be allowed?
  max-name-length: 200

  # When the player lefts the server, delete his tab name?
  clear-player-tabname-on-quit: false

  # Enable color codes in tab names?
  # false - disables all placeholders, symbols and color codes.
  enable-color-code: true

  # Enable default color? (If the player has not written a color code, this color will be given by default.)
  default-color:
    enable: false
    color: "&6"

  # In these worlds you can't change the tab name
  disabled-worlds:
  #- myworld

  # Which names can not be used?
  restricted-names:
  - tabname

#=========================================#
#             Plugin Settings             #
#=========================================#
# Check for updates?
check-update: true

# Download releases to \releases folder?
# This only works if the "check-update" is true.
download-updates: true

# Log plugin messages to console?
logconsole: true

# DO NOT CHANGE THIS!
config-version: 21
