# Hook plugins
hook:
  # Hooks into PlaceholderAPI to use custom placeholders.
  placeholderapi: true

  # Hooking to my RageMode plugin. (https://www.spigotmc.org/resources/69169/)
  # If true, will disable the tablist, groups and the tablist objects, while
  # running a game.
  RageMode: false

# Different playerlist in different world.
per-world-player-list: false

# Fake players that are on the tab.
enable-fake-players: false

# Ignoring vanished players in %online-players% placeholder.
# true - does not count the vanished players to placeholder.
# Requires Essentials or SuperVanish plugin!
ignore-vanished-players-in-online-players: false

# true - it counts vanished staffs to %staff-online% placeholder that
# have "tablist.onlinestaff" permission set.
# false - will not count vanished staff in the %staff-online% placeholder
# even if you have permission or not
# Requires Essentials or SuperVanish plugin!
count-vanished-staffs: true

# Hides player from tab when afk status.
# Requires Essentials plugin!
hide-player-from-tab-when-afk: false

# Hides all players from the player list (tab).
# This removes all players from the tab list, but the player that has the
# group set is retained as it is not changed during removal, so your group
# will be restored if this option is disabled.
# The "per-world-player-list" will not works if this enabled.
hide-players-from-tablist: false

# Placeholder formatting
placeholder-format:
  # When the player changes the afk status, changes the tablist name format.
  afk-status:
    enable: false

    # Should show the afk format in right or left side?
    # true - displays in right side
    # false - displays in left side
    show-in-right-or-left-side: true

    # Show the player group if the player afk?
    show-player-group: true

    # When the player is afk
    format-yes: "&7 [AFK]&r "
    # When the player is not afk
    format-no: ""

    # Sort afk players to the end of the tablist?
    sort-last: false

  time:
    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    # Or google it: "what is my time zone"
    time-zone: "GMT0"

    # Use system default time zone instead of searching for that?
    use-system-zone: false

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Used for %server-time% placeholder.
    time-format:
      format: "mm:HH"
    # Used for %date% placeholder.
    date-format:
      format: "dd/MM/yyyy"

  # Ping color format for %ping% placeholder.
  ping:
    enable: true

    # Use color coding "&" for color.
    good-ping:
      color: "&a"
      amount: 200
    medium-ping:
      color: "&6"
      amount: 500
    bad-ping: "&c"

  # TPS color format for %tps% placeholder.
  tps:
    enable: true

    # Use color coding "&" for color.
    good-tps:
      color: "&a"
      amount: 18.0
    medium-tps:
      color: "&6"
      amount: 16.0
    bad-tps: "&c"

# Custom variables that will be replaced in tablist.
# This useful when we are creating a lot of lines with the same name.
# Usage: <nameOfPlaceholder>: "&6Text..."
custom-variables:
  <name>: "&5&o%player%"
  <lines>: "&5&m======================"

# Enables to change prefix & suffix in player tablist.
# WARNING! Overwrites the tabname function.
change-prefix-suffix-in-tablist:
  enable: false

  # Refresh interval in seconds, if using animation then counts in ticks.
  # Set to 0 if you don't want to refresh the groups.
  # If 0 you will required to execute the /tl rl command, to reload the groups.
  refresh-interval: 30

  # Do you want to use animation in groups?
  # This creates a new task scheduler when this enabled.
  # If this true, then you need to change the refresh interval such as 4, because counting in ticks.
  # If this false, then back to seconds interval.
  enable-animation: false

  # Disable groups in the given worlds.
  disabled-worlds:
    # Use the list as white list or not?
    # If true - Using the white list option and all worlds should be given to the list
    # to show in the specified worlds.
    # If false (default) - Using the disabled list option and if a world is given in the list
    # the groups will be disabled in that world.
    use-as-whitelist: false
    list:
    #- myWorld

  # This for lazy users is designed to automatically add groups to the list of tablists every time
  # there is a reload, so the user has less to do.
  # If a plugin does not support Vault, it will not be added.
  sync-plugins-groups-with-tablist: true

  # This option allows you to use a different scoreboard to run groups if there is a problem
  # with other scoreboard plugins. If it doesn’t happen that the scoreboard disappears,
  # you don’t need to change it.
  use-own-scoreboard: false

  # Hide player group in tablist when the player is vanished?
  # Required Essentials plugin!
  hide-group-when-player-vanished: false

  # Hide player group in tablist when the player is afk?
  # Required Essentials plugin!
  hide-group-when-player-afk: false

  # Use the essentials nickname instead of player original name?
  # true - Using this format: "prefix playerNickName suffix"
  # false - Using this format: "prefix playerOriginalName suffix"
  use-essentials-nickname: false

  # Prefer using the players primary Vault group for choosing the groups.yml group?
  # true - player will be assigned their primary vault group where possible, after that groups from groups.yml will be applied in descending order
  # false - groups from groups.yml will be applied in descending order
  prefer-primary-vault-group: false

# Tablist objective types
# Shows your current health (with life indicator), shows your current ping or a custom placeholder
# that shows number.
tablist-object-type:
  enable: false

  # Types:
  # ping - ping of player
  # health - health of player
  # custom - custom value
  type: ping

  # The refresh interval when the objects are refreshing.
  # Note: The health is not updating auto due to display issues.
  refresh-interval: 3

  # In which worlds not to display the object? (world names)?
  disabled-worlds:
  #- testingWorld

  # Objective settings
  object-settings:
    # The player health (life) the player's name indicates the right side.
    health:
      # Blacklisted players who do not show the health in tab.
      blacklisted-players:
      - exampleplayer
      - players

    # It only accepts number-ending placeholders, like %level%
    # If it double-number ending, it will replaces the dot "." from the number.
    custom:
      value: "%level%"

# Changing player tablist name with unlimited characters.
tabname:
  # Allow to change player tab name.
  enable: false

  # Use the Essentials nickname instead of tab name?
  use-essentials-nickname: false

  # How many letters should be allowed?
  max-name-length: 200

  # When the player left the server, delete the tab name?
  clear-player-tabname-on-quit: false

  # Enables color coding for tab names. ("&")
  # false - disables all placeholders, symbols, and color codes.
  enable-color-code: true

  # Enable the default color. (If the player has not written a color code, this color will be given by default.)
  default-color:
    enable: false
    color: "&6"

  # Which worlds can not be change the tab name?
  disabled-worlds:
  #- myworld

  # Which names can not be used?
  blacklist-names:
  - tabname

#=========================================#
#             Plugin Settings             #
#=========================================#
# Check for updates.
check-update: true

# Download releases to \releases folder
# This only works if the "check-update" is true.
download-updates: true

# Log plugin messages into console.
logconsole: true

# DO NOT CHANGE THIS!
config-version: 19
